### ISSUE TITLE
Need exception handling if only negative eigenvalues in classic_mds

### ISSUE THREAD

**Issue by robertfeldt** [JuliaStats/MultivariateStats.jl#10]
I run classic_mds at a late stage in a long set of processing steps but got the warning that there were only 0 non-negative eigenvalues. Since the data was large I can't paste it in here. Maybe just throw an exception if there are less than p eigen values that are above 0? Or just select the largest ones?

**Comment by jiahao** [comment]
The only situations I have seen this situation occur stem from pathological inputs, so I would advise you to verify what you are trying to calculate.

I don't understand your point about "just throw an exception if there are less than p eigen values that are above 0? Or just select the largest ones?". If there are k<p eigenvalues, the code picks all k corresponding eigenvectors and pads the remaining coordinates with 0s and returns you that as an answer already.

Without a concrete example I can only point you to a justification of the current behavior. Consider what classical multidimensional scaling is trying to do, which is to embed points in a k-dimensional space in a way that best preserves the pairwise distances in a least-squares sense. The problem is equivalent to finding the k eigenvectors of distance matrix, suitably centered, corresponding to the k largest eigenvalues. The reason why the code only picks positive eigenvalues is because picking any negative eigenvalues actually makes the solution worse, and the correct solution to the least squares problem is to keep only the projection into the subspace with positive inertia. We could keep solutions that have a nonzero projection into the nullspace, but that corresponds to a particular choice of regularization which I am not sure is useful. I think it is better to warn users that something has gone wrong.

**Comment by jiahao** [comment]
One quick question - are you passing the entire distance matrix to classical_mds, or is it possible that your code is only computing the upper half or lower half of the distance matrix? (I think our implementation currently assumes that both halfs are calculated.)

**Comment by robertfeldt** [comment]
Hmm, it would be ok if it warned and returned something but it does not. It fails on line 80 since:

                ord = ord[1:m]

fails since m = i-1 and i is 1 since the first eigenvalue is < 0. I understand its a pathological case but I still don't think the solution is to exit with an error on line 80, imho.

The distance matrix is complete and symmetric, yes.

**Comment by robertfeldt** [comment]
BTW, the title of this issue was misleading... ;)

**Comment by jiahao** [comment]
Ah, ok. I can fix the handling of the case where all the eigenvalues are nonpositive.

**Comment by jiahao** [comment]
That line should not throw an error when m=0. `1:0` is an empty range in Julia and indexing into `ord` should give an empty vector:

```jl
julia> [1, 2, 3, 4, 5][1:0]
0-element Array{Int64,1}
```

Can you post the actual error message you are getting?

What version of Julia are you running?

**Comment by robertfeldt** [comment]
Sorry I was recollecting the bug from memory and misremembered the line. I managed to replicate it now though on Julia 0.3.7 and I did a 

     @show dists

before calling classic_mds:

    dists => [1.0 0.5 0.3181818181818182 0.38095238095238093 0.6111111111111112 0.36363636363636365 0.3333333333333333 0.4444444444444444 0.45454545454545453 0.38095238095238093
     0.5 1.0 0.3333333333333333 0.4166666666666667 0.32 0.37037037037037035 0.35 0.38461538461538464 0.38461538461538464 0.4
     0.3181818181818182 0.3333333333333333 1.0 0.38095238095238093 0.125 0.22727272727272727 0.47058823529411764 0.35294117647058826 0.2608695652173913 0.21052631578947367
     0.38095238095238093 0.4166666666666667 0.38095238095238093 1.0 0.17391304347826086 0.2962962962962963 0.38095238095238093 0.45454545454545453 0.3076923076923077 0.5454545454545454
     0.6111111111111112 0.32 0.125 0.17391304347826086 1.0 0.5 0.15 0.391304347826087 0.38095238095238093 0.3333333333333333
     0.36363636363636365 0.37037037037037035 0.22727272727272727 0.2962962962962963 0.5 1.0 0.2857142857142857 0.44 0.4 0.3181818181818182
     0.3333333333333333 0.35 0.47058823529411764 0.38095238095238093 0.15 0.2857142857142857 1.0 0.42105263157894735 0.45 0.23529411764705882
     0.4444444444444444 0.38461538461538464 0.35294117647058826 0.45454545454545453 0.391304347826087 0.44 0.42105263157894735 1.0 0.5416666666666666 0.5555555555555556
     0.45454545454545453 0.38461538461538464 0.2608695652173913 0.3076923076923077 0.38095238095238093 0.4 0.45 0.5416666666666666 1.0 0.4
     0.38095238095238093 0.4 0.21052631578947367 0.5454545454545454 0.3333333333333333 0.3181818181818182 0.23529411764705882 0.5555555555555556 0.4 1.0]
    WARNING: Gramian has only 0 positive eigenvalue(s)
    ERROR: BoundsError()
    in getindex at array.jl:246
    in classical_mds at /Users/feldt/.julia/v0.3/MultivariateStats/src/cmds.jl:88
    in measure_scaling at /Users/feldt/tmp/cmds_bug.jl:58
    in measure_scaling at /Users/feldt/tmp/cmds_bug.jl:44
    in include at /Applications/Julia-0.3.7.app/Contents/Resources/julia/lib/julia/sys.dylib
    in include_from_node1 at loading.jl:128
     in process_options at /Applications/Julia-0.3.7.app/Contents/Resources/julia/lib/julia/sys.dylib
    in _start at /Applications/Julia-0.3.7.app/Contents/Resources/julia/lib/julia/sys.dylib
    while loading /Users/feldt/tmp/cmds_bug.jl, in expression starting on line 72

**Comment by jiahao** [comment]
Thanks for the report; that was helpful. The problem was in the code that tried to check for degenerate eigenvalues.

I think the distance matrix you want to use should work with multidimensional scaling. In this case the distance matrix becomes entirely negative definite after centering with `dmat2gram`, while the code assumes the matrix always becomes entirely positive definite.
