### ISSUE TITLE
Stable docs link 404-ing

### ISSUE THREAD

**Issue by IanButterworth** [JuliaStats/MultivariateStats.jl#181]
The link on the readme https://juliastats.org/MultivariateStats.jl/stable

**Comment by wildart** [comment]
I cannot figure out what is going on. It looks like some security settings on repo are not set properly, a SSH key perhaps. The documenter fails with `Failed to add the RSA host key for IP address '192.30.255.112' to the list of known hosts (/home/runner/.ssh/known_hosts).`

I do not have access to repo settings. Any help! @timholy @nalimilan @ararslan 

Ref #161

**Comment by ararslan** [comment]
I've increased your permissions, @wildart, so you should be able to access settings. As far as I can tell, everything is configured properly and the reason why there are no stable docs is because https://github.com/JuliaStats/MultivariateStats.jl/commit/99ee965df3a8e136ff2d0fcb10456b434e1f9001 came in after the tag. It should show up with the next release. In the meantime, there's probably a way to post-hoc deploy documentation for tagged versions but I don't know what it is. You could ask in #documentation in the Julia Slack.

**Comment by wildart** [comment]
Docs are available now.
