### ISSUE TITLE
Possible inconsistency in PCA matrix dimensions?

### ISSUE THREAD

**Issue by raphaelsaavedra** [JuliaStats/MultivariateStats.jl#55]
Documentation for the PCA `fit` function states the following:

> Perform PCA over the data given in a matrix `X`. Each column of `X` is an observation.

> Let (d, n) = size(X) be respectively the input dimension and the number of observations

Which means if `X` is an **d x n** matrix, then `X` has **n** observations of **d** variables/features (kinda counter-intuitive to me, since we generally consider variables as columns)

Now, correct me if I'm wrong, when doing PCA one should centralize all variables by subtracting their means. So, after doing that, we now have matrix `X_centralized`, whose **d** rows have zero mean. So far, so good.

I then do `pcaResult = fit(PCA, X_centralized)` and therefore obtain the PCA model. `indim` is listed as **d**, in my case 44. However, when checking the correlation matrix of the principal components, `cor(pcaResult.proj)`, I verify the correlations are significant, which means PCA wasn't done correctly, since correlations should be zero.

I then do the opposite: I subtract the mean of each *observation*, not variable, which seems nonsensical. I use the `fit` function and obtain the PCA model. `indim` is listed as **n**, which in my case is 50 thousand. However, the correlation matrix in this case is zero as we should expect from a correct PCA!

Am I doing something wrong? Or is documentation incorrect and matrix `X` should have variables on columns instead of rows?

**Comment by raphaelsaavedra** [comment]
So apparently I might have gotten confused about the meaning of `indim`. I now realized `indim` represents the dimension of the observation space, which clears up some of my questions. However, I still think the sentence "Each column of `X` is an observation." in the documentation should be reworded to "Each column of `X` is a variable/feature."

Am I correct?

**Comment by wildart** [comment]
Since Julia arrays are stored in [column-major order](https://docs.julialang.org/en/stable/manual/performance-tips/#Access-arrays-in-memory-order,-along-columns-1), the design of this package follows such characteristic. Every observation is stored as column for better access to a complete set of observation data, and every feature is a row. Documentation is correct when it describes input parameters. This is just the language feature.

Indeed, `indim` shows the dimension of the observation space. So, I your first post you got confusing result because you used transposed matrix for input.

**Comment by raphaelsaavedra** [comment]
Hello, thank you for the quick answer. Indeed I got confused with `indim`. Still, I'm still somewhat confused.
In my code, each variable is a column, with the rows representing observations. After subtracting the mean, I use the fit function with the transpose function as argument, since variables need to be in rows. However, that results on correlated projections as I stated in the OP. On the other hand, this doesn't happen when I use the original matrix. That's why I thought maybe documentation is mistaken. Can you maybe point out where my mistake is? 

Thanks a lot.

**Comment by andreasnoack** [comment]
Just a small comment. When there is a matrix algorithm (as is the case for PCA), there isn't an advantage in using columns as observations. Least squares in LAPACK is a good example of that since Fortran is column major and yet  LAPACK's least squares solver assumes that observations by rows. There will only be an advantage in storing observations by columns when the algorithm processes an observation at a time but for dense problems that is really inefficient.

**Comment by raphaelsaavedra** [comment]
Andreas,

That's a very interesting fact that I did not know of. Thanks for the advice.
